// GENERATED by scripts/build-dht-worker.mjs — do not edit by hand.
declare const require: (moduleName: string) => unknown;

let cachedSource: string | null | undefined;

export function resolveDhtWorkerBundle(): string | null {
  if (cachedSource !== undefined) return cachedSource;
  const loaded = require("./dht-worker.bundle.js");
  cachedSource = typeof loaded === "string" ? loaded : null;
  return cachedSource;
}
